### ISSUE TITLE
Create production UI

### ISSUE THREAD

**Issue by permafrost06** [permafrost06/DiagMan#61]
This is our penultimate step to prod. The flow will be like this:
* (New sign in) Sign-in -> Main page
* (Signed-in user) Enter pin -> Main page

From main page, the following pages can be accessed:
* Tests management
* Statistics
* Settings

Settings page will have the following:
* SMS: Set SMS message (+ see preview), see SMS balance, set default SMS status<sup>1</sup>, change SMS token (advanced)
* User Management (admin only): See all users, create, modify, delete users
* Account Management: Set PIN, Log out

---
## Fonts
Heading: [Space Grotesk](https://fonts.google.com/specimen/Space+Grotesk)
Body: [Open Sans](https://fonts.google.com/specimen/Open+Sans)

## Colors
Text primary: Pure black (#000000)
Background primary: pure white (#FFFFFF)
Neutral: grey (#595959)
Accent color: #820097
Danger color: #F24E1E

---

## Pages to create:
- [x] Sign-in (with password/with PIN if logged in)
- [x] Main/home/landing page
- [x] Add patient
- [x] Add report to patient
- [x] Settings
    - [x] Tests management
        - view, add, edit, delete tests
    - [x] Report templates management
        - view, add, edit, delete report templates
    - [x] Account management
        - change name
        - change password
        - change pin
        - log out
- [x] Invoice print layout ([copy from v2](https://github.com/permafrost06/caseDB/blob/master/src/views/InvoiceView.vue))
- [x] Report print layout ([copy from v2](https://github.com/permafrost06/caseDB/blob/master/src/views/ReportView.vue))

## Tasks:
- [x] Decide color scheme
- [x] Select font(s)

Figma design: https://www.figma.com/file/yNYX7nIJE5xRUsKW5g4xlT/Clinic-web-app-(Copy)?type=design&node-id=0%3A1&mode=design&t=NhUwFtOOjGfgECKI-1

We are probably not going to use most of the design from this apart from some stuff e.g. notification holder, chart design etc.

----------
~~1: whether the "Send SMS" checkbox is checked by default when creating report.~~

**Comment by permafrost06** [comment]
## Fonts
Heading: [Space Grotesk](https://fonts.google.com/specimen/Space+Grotesk)
Body: [Open Sans](https://fonts.google.com/specimen/Open+Sans)

## Colors
Pure black (#000000), pure white (#FFFFFF), and grey (#595959). An accent color may be used, to be decided later. Please use CSS vars for colors.

**Comment by protibimbok** [comment]
Should we use RGB values as colors?
```css
:root {
    --clr-accent: 0, 114, 143;
}
```
Then in css we'll have the option to use like:
```css
button {
    background: rgb(var(--clr-accent));
}
button:hover  {
    background: rgba(var(--clr-accent), 0.9);
}
```

This is what tailwind does behind the scene.

**Comment by permafrost06** [comment]
If that benefits us, then yes, but will it benefit us? How?

**Comment by protibimbok** [comment]
Its benefit is mainly to accent, danger, success & warning styles. As the background, text & the border is just different variation of the same color. In these cases, we won't have to specify them separately we can just apply different alpha.

**Comment by permafrost06** [comment]
Okay, we'll use similarly structured CSS vars, then. Approved.

**Comment by permafrost06** [comment]
We need a new page: Reset password

**Comment by permafrost06** [comment]
Test management page will be inside settings page

**Comment by permafrost06** [comment]
@protibimbok `--clr-black` and `--clr-white` will be problematic if we decide to change the colors. Please update the color vars like this:

Text primary: Pure black (#000000)
Background primary: pure white (#FFFFFF)
Neutral: grey (#595959)
Accent color: #820097
Danger color: #F24E1E

Please let me know if you have any comments/suggestions about the naming.

**Comment by permafrost06** [comment]
Settings:
appearance
	theme -> light, dark (with preview photos)
	font size -> sm, m, l, xl
	table
		default sort
		cols to show
		resize

tests
	view, add, edit, delete tests

report templates
	view, add, edit, delete report templates

sms
	view sms balance
	change sms message + see preview
	set default sms state

printing
	invoice layout
	report layout

charts
	???

notifications
	???

account
	change name
	change password
	change pin
	log out

manage users (admin only)
	view, edit users
	request deletion, request new account

about

advanced
	turso db url
	api (worker) url
	sms, api, vite_auth, turso tokens
	color vars
		primary
		secondary
		...
		accent
		danger
	change fonts
		heading
		body
	padding, margin

**All settings don't have to be implemented on v3.0. Only tests, report templates, and account settings.**

**Comment by permafrost06** [comment]
Please implement **pagination**, **sorting**, **filtering** for patient list.
* When clicked on the sort icon next to a header, that column will be sorted and the icon will show the sort direction. Clicking on the sort icon again will change the sort direction. It'll also update the sort button text. (Implement sort button actions later).
* Implement the discord style searchbar for filtering: all fields will be searched for the search string. `field:search-string` will search only in the specified field. Remove the filter button. Clicking on the filter icon next to a header will move focus to the searchbar and add the field name to the searchbar. For example: when clicked on the filter icon next to "Type", `type:` will be inserted to the searchbar.

**Comment by permafrost06** [comment]
The icons for status field and report button in patients list may be ignored for now.

**Comment by permafrost06** [comment]
Reset password page is not necessary. Password reset will be done manually by contacting developer.

**Comment by permafrost06** [comment]
v2 invoice page:
![image](https://github.com/permafrost06/caseDB/assets/16163320/874588e4-970b-481b-80ba-b0345ccd895b)
![image](https://github.com/permafrost06/caseDB/assets/16163320/fa12454d-6de5-470b-8259-0e6427323020)

**Comment by permafrost06** [comment]
closed by #64
